version: '3.8'

services:
  ml-backend:
    build: .
    container_name: alfa_ml_backend
    ports:
      - "8000:8000"
    volumes:
      # Прокидываем модели (чтобы обновлять их без пересборки образа)
      - ./models:/app/models
      
      # ИСПРАВЛЕНО: Прокидываем папку с CSV данными
      # На хосте папка data -> В контейнере /app/data
      - ./data:/app/data
    environment:
      - WORKERS=1
      - PYTHONUNBUFFERED=1  # Чтобы логи в консоли появлялись сразу
    restart: always